sef_roboter:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # JointTrajectoryController ----------------------------------
  joints_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    gains:
      joint_1: {p: 3000.0, i: 100, d: 750.0, i_clamp_min: -500, i_clamp_max: 500}
      joint_2: {p: 10000.0, i: 250, d: 1000.0, i_clamp_min: -800, i_clamp_max: 800}
      joint_3: {p: 3000.0, i: 500, d: 500.0, i_clamp_min: -500, i_clamp_max: 500}
      joint_4: {p: 100.0, i: 10, d: 25.0, i_clamp_min: -500, i_clamp_max: 500}
      joint_5: {p: 1000.0, i: 100, d: 50.0, i_clamp_min: -500, i_clamp_max: 500}
      joint_6: {p: 50.0, i: 0, d: 0.0, i_clamp_min: 0, i_clamp_max: 0}